### ISSUE TITLE
Pointcloud partially flickering (incomplete) in rviz.

### ISSUE THREAD

**Issue by batzor** [ouster-lidar/ouster-ros#110]
**Describe the bug**
PointCloud flickering in RVIZ. `ros2_ouster_driver` works without problem.

**To Reproduce**
Steps to reproduce the behavior (steps below are just an example):
1. ROS Foxy
2. Clone `ros2-foxy` branch and colcon build. 
3. `ros2 launch ouster_ros sensor.independent.launch.py`
4. params:
```
ouster/os_sensor:
  ros__parameters:
    sensor_hostname: '192.168.2.82'
    udp_dest: '192.168.2.81'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '512x10'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'LEGACY'
    metadata: ''
    lidar_port: 7502
    imu_port: 7503
ouster/os_cloud:
  ros__parameters:
    tf_prefix: ''
    timestamp_mode: 'TIME_FROM_ROS_TIME'
```

**Screenshots**
![Screencast 2023-04-24 15_22_16](https://user-images.githubusercontent.com/32958247/233916464-4dc68756-5d06-4688-a0a4-15aacefc999d.gif)

**Platform (please complete the following information):**
- Ouster Sensor? OS-0-64-U13
- Ouster Firmware Version? v2.4.0
- ROS version/distro? Foxy 
- Operating System? Ubuntu 20.04
- Machine Architecture? ARM
- git commit hash (if not the latest).
