### ISSUE TITLE
Unable to launch `os_driver` node after update

### ISSUE THREAD

**Issue by leonardogargani** [ouster-lidar/ouster-ros#174]
**Describe your question**

Today I updated my local copy of this repository and I became unable to obtain data from my OS-1-64 lidar.

Running `ros2 launch ouster_ros driver.launch.py` I obtain the following error:
```
[INFO] [launch]: All log files can be found below /home/airlab/.ros/log/2023-07-24-17-23-54-796551-airlab-9842
[INFO] [launch]: Default logging verbosity is set to INFO
/home/airlab/bunker_sensors_ros2/install/ouster_ros/share/ouster_ros
/home/airlab/bunker_sensors_ros2/install/ouster_ros/share/ouster_ros/config/viz.rviz
/home/airlab/bunker_sensors_ros2/install/ouster_ros/share/ouster_ros
/home/airlab/bunker_sensors_ros2/install/ouster_ros/share/ouster_ros/config/viz.rviz
[INFO] [rviz2-1]: process started with pid [9854]
[INFO] [os_driver-2]: process started with pid [9856]
[rviz2-1] [INFO] [1690212235.091298863] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1690212235.091338737] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1690212235.104852258] [rviz2]: Stereo is NOT SUPPORTED
[os_driver-2] [INFO] [1690212235.138739316] [ouster.os_driver]: TIME_FROM_ROS_TIME timestamp mode specified. IMU and pointcloud messages will use ros time
[os_driver-2] [INFO] [1690212235.138801296] [ouster.os_driver]: Will send UDP data to 192.168.1.101
[os_driver-2] [INFO] [1690212235.207991526] [ouster.os_driver]: Sensor os1-xxxxxxxxxxxx.local configured successfully
[os_driver-2] [INFO] [1690212235.208091860] [ouster.os_driver]: Starting sensor os1-xxxxxxxxxxxx.local initialization...
[os_driver-2] [2023-07-24 17:23:55.208] [ouster::sensor] [info] initializing sensor: os1-xxxxxxxxxxxx.local with lidar port/imu port: 7502/7503
[rviz2-1] [INFO] [1690212235.246414989] [rviz2]: Stereo is NOT SUPPORTED
[os_driver-2] [INFO] [1690212246.896064604] [ouster.os_driver]: No metadata file was specified, using: os1-xxxxxxxxxxxx-metadata.json
[os_driver-2] [INFO] [1690212246.896372716] [ouster.os_driver]: Wrote sensor metadata to os1-xxxxxxxxxxxx-metadata.json
[os_driver-2] [INFO] [1690212246.896398075] [ouster.os_driver]: ouster client version: 0.8.1+d730798-release
[os_driver-2] product: OS-1-64, sn: xxxxxxxxxxxx, firmware rev: v2.4.0
[os_driver-2] lidar mode: 1024x10, lidar udp profile: LEGACY
[os_driver-2] [INFO] [1690212246.897362299] [ouster.os_driver]: reset service created
[os_driver-2] [INFO] [1690212246.897838660] [ouster.os_driver]: get_metadata service created
[os_driver-2] [INFO] [1690212246.898126568] [ouster.os_driver]: get_config service created
[INFO] [launch.user]: os_driver activating...
[os_driver-2] [INFO] [1690212246.898402976] [ouster.os_driver]: set_config service created
[ERROR] [os_driver-2]: process has died [pid 9856, exit code -11, cmd '/home/airlab/bunker_sensors_ros2/install/ouster_ros/lib/ouster_ros/os_driver --ros-args -r __node:=os_driver -r __ns:=/ouster --params-file /home/airlab/bunker_sensors_ros2/install/ouster_ros/share/ouster_ros/config/driver_params.yaml'].
```

I also tried using the *sensor.launch.xml* launch file, but the result did not change.
I then decided to revert back to the previous commit that was working for me, but again the same error was shown.
All the tests above lead to the same result both with ROS Humble and ROS Iron, using the *ros2* branch.

I can say for sure that the lidar has no hardware/firmware problem and it is properly connected to the computer, since I am able to visualize pointclouds using the [ouster-cli](https://static.ouster.dev/sdk-docs/cli/overview.html) utility.

To make an attempt while using ROS Humble/Iron, since *ouster-cli* is ROS-independent, I used  [ouster-lidar/ouster-ros](https://github.com/ouster-lidar/ouster-ros) drivers and the pointclouds were correctly displayed on Rviz2.

For completeness, here is the content of *driver_params.yaml*:
```yaml
ouster/os_driver:
  ros__parameters:
    sensor_hostname: 'os1-xxxxxxxxxxxx.local'
    udp_dest: '192.168.1.101'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x10'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'LEGACY'
    metadata: ''
    lidar_port: 7502
    imu_port: 7503
    sensor_frame: os_sensor
    lidar_frame: os_lidar
    imu_frame: os_imu
    point_cloud_frame: os_lidar 
    proc_mask: IMG|PCL|IMU|SCAN
    scan_ring: 0
    use_system_default_qos: false
```

**Platform:**
- Ouster Sensor: *OS-1-64*
- Ouster Firmware Version: *2.4.0*
- ROS version/distro: *humble*, *iron*
- Operating System: *Ubuntu 22.04 LTS*
- Machine Architecture: *x64*
