### ISSUE TITLE
Low-frequency lidar pointcloud messages with ROS2

### ISSUE THREAD

**Issue by SimonGiampy** [ouster-lidar/ouster-ros#278]
**Low-frequency and unstable lidar pointcloud messages transmission with ROS2 Humble and Iron**

The OS1-64 lidar with the ROS2 driver has very low frequency and unstable messages transmission. Sometimes the rate of messages transmission drops below 1Hz, but it is often unpredictable. Most of the time the behavior in data transmission is unstable: it sends messages "in a burst", meaning that it sends few messages, than drops silent for about 1 second, then restarts the transmission. Overall the lidar pointcloud transmission is not reliable at all, making the sensor unusable with ROS2. There are other times in which the lidar seems to work better, but this is unpredictable. We currently do not know whether the problem is at ROS Middleware level, or at ROS-wrapper driver level. The problem arises with both ROS2 Humble and Iron distributions, even in a fresh linux installation.

**What we tried**:
- Ouster Studio shows the Lidar working perfectly fine, even at 20Hz, so it is not a hardware malfunctioning problem
- Different middleware implementations showed the same problem. FastDDS shows missing pointcloud messages, dropping the transmission rate. CycloneDDS shows missing chunks of pointcloud, being received "in sectors" and not in their entirety.
- Changed resolution of the pointcloud: even the lowest 512x10 doesn't solve the issue
- LIDAR IMU messages received at correct rate of 100Hz
- Used realtime linux kernel but didn't change anything

**Platform**
- Ouster Sensor: OS1-64
- Ouster Firmware Version: v2.4.0
- ROS version/distro: ROS2 Humble & Iron
- Middleware DDS: FastDDs & CycloneDDS
- Operating System: Linux Ubuntu 22.04
- Machine Architecture: Intel 12th gen processor, x64
- git commit: branch ros2
- lidar connected via ethernet to the PC

**Screenshot of the problem**
![image](https://github.com/ouster-lidar/ouster-ros/assets/13204484/848d2dac-4196-42be-ae88-ace0c085a88b)

As you can see, this screenshot shows an unstable rate of reception of pointcloud messages. In this case it is around 4hz, but sometimes drops below 1Hz.

**Driver configuration parameters used**:
```yaml
ouster/os_driver:
  ros__parameters:
    
    sensor_hostname: 'os1-991942000600.local'

    udp_dest: ''
    
    mtp_dest: ''
   
    mtp_main: false
    
    lidar_mode: '1024x10'
    
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    
    ptp_utc_tai_offset: -37.0
    
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    
    metadata: ''
    
    lidar_port: 7502
    
    imu_port: 7503
    
    sensor_frame: os_sensor
    
    lidar_frame: os_lidar
    
    imu_frame: os_imu
    
    point_cloud_frame: os_lidar 
    
    proc_mask: PCL|IMU
    
    scan_ring: 0
    
    use_system_default_qos: false
    
    point_type: original
```
